version: '3'

services:

  sanic-api:
    platform: linux/x86_64 # Needed for Mac M1
    
    build:
      context: ./api/
      dockerfile: Dockerfile
    
    ports:
     - '5000:80'
    
    env_file: ./.env